"""Initial migration

Revision ID: 242e2261de8c
Revises: 8702315c272b
Create Date: 2025-03-14 10:38:57.751137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242e2261de8c'
down_revision = '8702315c272b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('completed_date')
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
